name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Create .env file
      run: |
        echo "RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}" >> .env
        echo "RAZORPAY_KEY_SECRET=${{ secrets.DATABASE_URL }}" >> .env
        echo "PAYMENT_PORT=${{ secrets.PAYMENT_PORT }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "USER_GRPC_SERVER=${{ secrets.USER_GRPC_SERVER }}" >> .env
        echo "APPT_GRPC_SERVER=${{ secrets.APPT_GRPC_SERVER }}" >> .env
    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hosp-connect-payment-svc:latest

    # Tag and Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker tag hosp-connect-payment-svc:latest ${{ secrets.DOCKER_USERNAME }}/hosp-connect-payment-svc:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/hosp-connect-payment-svc:latest

        
